# Generated by Django 2.2.11 on 2020-05-21 17:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('start_on', models.DateField(default=django.utils.timezone.now)),
                ('ends_on', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
