# Generated by Django 2.2.11 on 2020-05-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnGroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learngroup',
            name='id',
            field=models.CharField(default='-', max_length=5, primary_key=True, serialize=False),
        ),
    ]
