# Generated by Django 2.2.11 on 2020-05-21 17:13

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('learnGroups', '0002_auto_20200521_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learngroup',
            name='ends_on',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='learngroup',
            name='start_on',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
