# Generated by Django 2.2.11 on 2020-05-22 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnGroups', '0004_auto_20200522_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learngroup',
            name='ends_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='learngroup',
            name='start_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
