# Generated by Django 2.2.11 on 2020-05-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnGroups', '0005_auto_20200522_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learngroup',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
