# Generated by Django 2.2.11 on 2020-04-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('ADM', 'Admin'), ('STD', 'Student'), ('TCH', 'Teacher')], default=('STD', 'Student'), max_length=50),
        ),
    ]
