# Generated by Django 2.2.11 on 2020-04-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('ADM', 'Admin'), ('STD', 'Student'), ('TCH', 'Teacher')], default='STD', max_length=50),
        ),
    ]
