# Generated by Django 2.2.11 on 2020-05-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200522_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='learn_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudLearnGroup', to='learnGroups.LearnGroup'),
        ),
    ]
