# Generated by Django 2.2.11 on 2020-05-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200522_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='learn_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudLearnGroup', to='learnGroups.LearnGroup'),
        ),
    ]
