# Generated by Django 2.2.11 on 2020-04-17 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='ends_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
