# Generated by Django 2.2.11 on 2020-05-25 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleItems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleitem',
            old_name='duration',
            new_name='end_at',
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='MONDAY', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='start_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
